sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    access-key-id: LTAI5tHExY7vg2CrtW6JrA68
    access-key-secret: BRr3AeOZurnnSwbVy9peLVCCoRAA0B
    bucket-name: web-sky-take-out-jayzhang
    endpoint: oss-cn-shenzhen.aliyuncs.com
